import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/layouts/Navbar";
import Footer from "../components/layouts/Footer";
// import normalFont from "./../fonts/mayaboit-normal.ttf";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const banglaFont = localFont({
  src: "../fonts/mayaboti-normal.ttf",
});

// export const metadata = {
//   title: {
//     default: "Hero Kidz",
//     template: "%s || Hero Kidz",
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Hero Kidz – Fun & Educational Toys for Kids",
    template: "%s | Hero Kidz",
  },
  description:
    "Hero Kidz is a kids-focused educational platform offering fun, interactive, and learning-based toys that help children grow smarter through play.",

  keywords: [
    "Hero Kidz",
    "kids toys",
    "educational toys",
    "learning toys",
    "kids products",
    "children toys online",
    "hero kidz toys",
  ],

  authors: [{ name: "Hero Kidz Team" }],
  creator: "Hero Kidz",
  publisher: "Hero Kidz",

  metadataBase: new URL("https://hero-kids-gamma.vercel.app"),

  openGraph: {
    title: "Hero Kidz – Fun & Educational Toys for Kids",
    description:
      "Discover fun and educational toys at Hero Kidz. Designed to help kids learn, grow, and enjoy every moment.",
    url: "https://hero-kids-gamma.vercel.app",
    siteName: "Hero Kidz",
    images: [
      {
        url: "https://i.ibb.co.com/CKCY1LbY/image.png", // homepage preview
        width: 1200,
        height: 630,
        alt: "Hero Kidz Homepage Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Hero Kidz – Fun & Educational Toys for Kids",
    description:
      "Fun meets learning at Hero Kidz. Explore educational toys that inspire creativity and growth.",
    images: ["https://i.ibb.co.com/CKCY1LbY/image.png"],
    creator: "@herokidz",
  },

  icons: {
    icon: "https://i.ibb.co.com/4wxJxdwn/image.png",
    apple: "https://i.ibb.co.com/4wxJxdwn/image.png",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  category: "Kids & Education",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar />
        </header>
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-302px)]">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
